version: "3"

services:
  api:
    image: vacinacao-img
    build: .
    ports:
        - 9000:8080
    environment:
        - AWS_REGION=us-east-1
        - AWS_ACCESS_KEY_ID=""
        - AWS_SECRET_ACCESS_KEY=""
