AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    # Your CORS hosts need to be in this format - note the two layers of quotes.
    Cors: "'*'"

# Our Python callback
Resources:
  VacinacaoFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 244978745220.dkr.ecr.us-east-1.amazonaws.com/vacinacao-app:0.10.3
      Events:
        GetSearch:
          Type: Api
          Properties:
            Path: /
            Method: get
        PostSearch:
          Type: Api
          Properties:
            Path: /search
            Method: post
    Metadata:
      DockerTag: vacinacaofunction:vacinacao-img
      DockerContext: ./webapp
      Dockerfile: Dockerfile
  VacinacaoFunctionIndexer:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 120
      MemorySize: 1024
      PackageType: Image
      ImageUri: 244978745220.dkr.ecr.us-east-1.amazonaws.com/vacinacao-app:0.10.3
      ImageConfig:
        Command:
          - "handler.reindex_handler"
      Role: arn:aws:iam::244978745220:role/vacinacao-app-VacinacaoFunctionRole-QWM4AIGVKOM2
      Events:
        Reindex:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
    Metadata:
      DockerTag: vacinacaofunction:vacinacao-img
      DockerContext: ./indexer
      Dockerfile: Dockerfile

Outputs:
  VacinacaoFunction:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"